app1/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
	url(r'^userhome', views.userhome),
	url(r'^detectorhome', views.detectorhome),
	url(r'^changepassword', views.changepassword),
	url(r'^upload', views.modelformupload),
    url(r'^displayfiles', views.displayfiles),
	url(r'^checkdocument', views.checkdocument),
	url(r'^history', views.history),
	url(r'^deletefile', views.deletefile),
]

data/data/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from login import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('login.urls')),
    url(r'^logout', views.logout, name='logout'),
    url(r'^user/', include('app1.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
	title = models.CharField(max_length=50,default='null')
	author = models.CharField(max_length=50, default='null') #clientid of the person who uploaded the file
	description = models.CharField(max_length=500, blank=True)
	accesslevel = models.CharField(max_length=50, default=4)
	document = models.FileField(upload_to='documents/')
	uploaded_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title
class DetectorUpload(models.Model):
	document = models.FileField(upload_to='detector/')
	clientid = models.CharField(max_length=50, default='null')
	username = models.CharField(max_length=50, default='null')
	designation = models.CharField(max_length=50, default='null')
	m = models.CharField(max_length=150, default='null') #retrieved from image
	mdash = models.CharField(max_length=150, default='null') #calculated from clientID
	status = models.CharField(max_length=20, default='Not Viewed') #culprit detected or not
	uploaded_at = models.DateTimeField(auto_now_add=True)

app1/forms.py
from django import forms
from app1.models import Document, DetectorUpload

class ChangepwdForm(forms.Form):
	def __init__(self, *args, **kwargs):
		super(ChangepwdForm, self).__init__(*args, **kwargs)
		self.fields['current'].widget.attrs = {
			'class' : 'form-control',
			'placeholder' : 'Current Password'
		}
		self.fields['new'].widget.attrs = {
			'class' : 'form-control',
			'placeholder' : 'New Password'
		}
		self.fields['reenter'].widget.attrs = {
			'class' : 'form-control',
			'placeholder' : 'Re-enter Password'
		}

	current = forms.CharField(max_length=50, widget=forms.PasswordInput)
	new = forms.CharField(max_length=50, widget=forms.PasswordInput)	
	reenter = forms.CharField(max_length=50, widget=forms.PasswordInput)

class DocumentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {
            'class': 'form-control',
            'placeholder': 'title'
        }
        self.fields['description'].widget.attrs = {
            'class': 'form-control',
            'placeholder': 'description'
        }
        self.fields['accesslevel'].widget.attrs = {
            'class': 'form-control',
            'placeholder': 'accesslevel',
        }


    title = forms.CharField(max_length=50)
    description = forms.CharField(max_length=500)
    accesslevel = forms.CharField(max_length=50)
    document = forms.FileField()

    class Meta:
        model = Document
        fields = ('title','description', 'accesslevel', 'document')

class DetectorUploadForm(forms.ModelForm):
    document = forms.FileField()
    class Meta:
        model = DetectorUpload
        fields = {'document'}

app1/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect	
from .forms import ChangepwdForm, DocumentForm, DetectorUploadForm
from login.models import LoginDetails
from app1.models import Document as doc, DetectorUpload
from django.views.decorators.cache import cache_control
import cv2
from PyPDF2 import PdfFileReader,PdfFileWriter
from reportlab.pdfgen import canvas
import subprocess
import codecs
from Crypto.Cipher import AES
from django.db.models import Q
from django.contrib import messages
# Create your views here.
k=[]
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def userhome(request):
	try:
		username = request.session['username']
		designation = request.session['access']
		clientid = request.session['clientid']
		levels = ['public','private','confidential','topsecret']
		context = {
		'username' : username,
		'designation' : levels[designation%4 - 1],
		'nbar' : 'home',
		}
	except:
		return HttpResponseRedirect('/')
	if designation == 5:
		del request.session['username']
		return HttpResponseRedirect('/')
	return render(request, 'app1/userHome.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def detectorhome(request):
	try:
		username = request.session['username']
		designation = request.session['access']
		clientid = request.session['clientid']
		context = {
		'username' : username,
		'nbar' : 'home',
		}
	except:
		return HttpResponseRedirect('/')
	if designation != 5:
		del request.session['username'] #end the session
		return HttpResponseRedirect('/') #redirect to login page	
	return render(request, 'app1/detectorHome.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def changepassword(request):
	try:
		username = request.session['username']
		designation = request.session['access']
		clientid = request.session['clientid']
	except:
		return HttpResponseRedirect('/')
	levels = ['public','private','confidential','topsecret']	
	if request.method == 'POST':
		form = ChangepwdForm(request.POST)
		if form.is_valid():
			current = form.cleaned_data['current']
			new = form.cleaned_data['new']
			reenter = form.cleaned_data['reenter']

			q = LoginDetails.objects.get(clientid=clientid)
			if q.password == current:
				if new == reenter:
					q.password = new
					q.save()
				else:
					return HttpResponse("new and reentered password doesn't match")
			else:
				return HttpResponse("incorrect password")
	else:
		form = ChangepwdForm()

	context = {
		'form' : form,
		'username' : username,
		'designation' : levels[designation%4 -1],
		'nbar' : 'changepass'
	}
	if designation == 5:
		return render(request, 'app1/detector_changePassword.html', context)
	else:
		return render(request, 'app1/user_changePassword.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def modelformupload(request):
	try:
		username = request.session['username']
		designation = request.session['access']
		clientid = request.session['clientid']
	except:
		return HttpResponseRedirect('/')
	if request.method == 'POST':
		form = DocumentForm(request.POST, request.FILES)
		if form.is_valid():
			if request.POST['accesslevel'] > str(designation):
				return HttpResponse("Access level not allowed")
			else:
				form.save()
				q = doc.objects.last()
				q.author = clientid
				q.save()

			return HttpResponseRedirect('/user/userhome')
	else:
		form = DocumentForm()
	levels = ['public', 'private', 'confidential', 'topsecret']
	context = {
		'form' : form,
		'designation': levels[designation%4 -1],
		'nbar':'uploaddoc',
		'username' : username,
	}
	if designation == 5:
		del request.session['username']
		return HttpResponseRedirect('/')
	return render(request, 'app1/user_uploadDocument.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def displayfiles(request):
	try:
		username = request.session['username']
		clientid = request.session['clientid']
		designation = request.session['access']
	except:
		return HttpResponseRedirect('/')
	q = doc.objects.filter(accesslevel__lte=designation)
	levels = ['public', 'private', 'confidential', 'topsecret']
	context = {
		'data': q,
		'nbar': 'displaydoc',
		'designation': levels[designation%4 -1],
		'username': username,
	}
	
	if request.method == 'POST':
		if request.POST.get('filename'): #filename is name attribute of the button clicked in template
			name = request.POST.get('filename')
			out = "documents/document-output.pdf"
			val = modify_file(name, clientid)
			if val == "success":
				return HttpResponseRedirect("/media/" + out)
			else:
				return HttpResponse("Embed failure")
	if designation == 5:
		del request.session['username']
		return HttpResponseRedirect('/')
	return render(request, "app1/user_searchDocument.html", context)

def modify_file(filename, clientid):
    q = LoginDetails.objects.filter(clientid=clientid)[0]
    cipher = q.cipher_text
    hash1 = q.hash_text

    #cipher embedding
    pixel_array = [ord(c) for c in cipher]
    del pixel_array[-1]
    # img = cv2.imread('/home/t3/projtest/actual/new/mysite/media/documents/image_small.png')
    img = cv2.imread('./media/documents/R_2.jpg')
	# print(img)
    for i in range(0, len(pixel_array), 1):
        img.itemset((55, i + 10, 0), pixel_array[i])

    #hash embedding
    pixel_array1 = [ord(c) for c in hash1]
    x = 58
    y = 10
    for i in range(len(pixel_array1) - 1, -1, -1):
        if (y >= img.shape[1]):
            y = 0
            x = x + 1

        img.itemset((x, y, 0), pixel_array1[i])
        y = y + 1
    # cv2.imwrite('/home/t3/projtest/actual/new/mysite/media/documents/image_small_hash.png', img)
    cv2.imwrite('./media/documents/R_2_hash.png', img)

    #embedding process
    # c = canvas.Canvas("/home/t3/projtest/actual/new/mysite/media/documents/watermark.pdf")
    c = canvas.Canvas("./media/documents/watermark.pdf")
    # c.drawImage("/home/t3/projtest/actual/new/mysite/media/documents/image_small_hash.png", 0, 0, preserveAspectRatio=True)
    c.drawImage("./media/documents/R_2_hash.png", 0, 0, preserveAspectRatio=True)
    c.save()

    output = PdfFileWriter()
    # newurl = "/home/t3/projtest/actual/new/mysite/media/" + filename
    newurl = "./media/" + filename
    input1 = PdfFileReader(open(newurl, "r+b"))
    num_pages = input1.getNumPages()
    # watermark = PdfFileReader(open("/home/t3/projtest/actual/new/mysite/media/documents/watermark.pdf", "r+b"))
    watermark = PdfFileReader(open("./media/documents/watermark.pdf", "r+b"))

    for pg in range(0, num_pages):
        page = input1.getPage(pg)
        page.mergePage(watermark.getPage(0))
        output.addPage(page)

    # finally, write "output" to document-output.pdf
    # outputStream = open("/home/t3/projtest/actual/new/mysite/media/documents/document-output.pdf", "w+b")
    outputStream = open("./media/documents/document-output.pdf", "w+b")
    output.write(outputStream)
    outputStream.close()
    return ("success")

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def checkdocument(request):
    if(k):
        messages.error(request, "Culprit: "+ k.pop()+ " is culprit")
    try:
        username = request.session['username']
        designation = request.session['access']
    except:
        return HttpResponseRedirect('/')
    if designation != 5:
        del request.session['username']  # end the session
        return HttpResponseRedirect('/')  # redirect to login page
    if request.method=='POST':
        form = DetectorUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            extraction()
        return HttpResponseRedirect('/user/history')

    else:
        form = DetectorUploadForm()

    context = {
        'username': username,
        'nbar': 'checkdoc',
        'form': form,
    }
    return render(request, "app1/detector_checkDocument.html", context)

def extraction():
	q = DetectorUpload.objects.last()
	name = str(q.document)
	# document_location = "/home/t3/projtest/actual/new/mysite/media/"
	document_location = "./media/"
	file_loc = document_location + name
	logo_loc = document_location + "detector/./z"

	#logo extraction from document
	subprocess.call(["pdfimages", "-png", "-p", "-l", "1", file_loc, logo_loc])

	#cipher extraction from logo
	im = cv2.imread(document_location + 'detector/z-001-000.png')
	cipher = []
	for i in range(0,24,1):
		cipher.append(im[55,i+10,0])
	cipher = ''.join(chr(c) for c in cipher)
	cipher=cipher + '\n'

    #decryption of cipher
	base64_data = cipher.encode('utf-8')
	cipher_text = codecs.decode(base64_data, 'base64')
	decryption_suite = AES.new('this is a key123', AES.MODE_CBC, 'This is an IV456')
	plain = decryption_suite.decrypt(cipher_text)
	plain = plain.decode('utf-8')
    #extaction of hash from logo
	x=58
	y=10
	reverse_hash=[]
	for i in range(0,128,1):
		if(y>=im.shape[1]):
			y=0
			x=x+1
		reverse_hash.append(im[x,y,0])
		y=y+1
	hash=reverse_hash[::-1]
	hash = ''.join(chr(c) for c in hash)  # join characters
	try:
		culprit = LoginDetails.objects.filter(Q(cipher_text=cipher) | Q(hash_text=hash))[0]
		print(culprit.clientid, culprit.username, culprit.hash_text)
		if culprit.hash_text == hash:
			print("Culprit's name is: {}".format(culprit.username))
			q.username = culprit.username
			q.designation = culprit.designation
			q.m = hash
			q.mdash = culprit.hash_text
			q.clientid = culprit.clientid
			q.status = 'Yes'
			q.save()

	except:
		print("Not detected")
		q.status = 'No'
		q.save()


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def history(request):
	try:
		username = request.session['username']
		designation = request.session['access']
	except:
		return HttpResponseRedirect('/')
	if designation != 5:
		del request.session['username']  # end the session
		return HttpResponseRedirect('/')  # redirect to login page

app1/templates/app1/detectorHome.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Leakage Detection</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <style>
    *{
      overflow: hidden;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">      
      <a class="navbar-brand navbar-colored" href="#">CSE3501</a>
    </div>

    <ul class="nav navbar-nav navbar-right">    
      <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Sign Out </a></li>
    </ul>
	
  </div>
</nav>

<div class="row color2">
  <div class="col-6 text-center">
    <h2><p class="color1">Leakage detection</p></h4>
  </div>  
</div>

<div class="row">
  <div class="row container" style="margin-left: 0.1rem">
    <ul class="nav nav-tabs">
      <li class="{% if nbar == 'home' %}active{% endif %}"><a href="/user/detectorhome/">Home</a></li>
      <li class="{% if nbar == 'changepass' %}active{% endif %}"><a href="/user/changepassword/">Change Password</a></li>
      <li class="{% if nbar == 'checkdoc' %}active{% endif %}"><a href="/user/checkdocument">Check Document</a></li>
      <li class="{% if nbar == 'history' %}active{% endif %}"><a href="/user/history">History</a></li>
    </ul>
  </div>

  <div class="row text-center">
  {% block content %}
  {% endblock %}

  </div>
</div>

  <div class="row text-right" style = " background-color: #f1fff1; positon:sticky ; bottom: 0; padding: 0">
      <p style="padding: 0; margin-right: 50px; margin-bottom:0;"><em>Username: </em><b class="color2" style="color: #1111ff;"> {{ username }}</b></p>
  </div>
</body>
</html>

app1/templates/app1/detector_changePassword.html
{% extends 'app1/detectorHome.html' %}

{% block content %}
    <form class="form-horizontal" method="POST" style="display: flex; justify-content: center;">
  {% csrf_token %}  
  <div class="form-group" style="padding-left: 50px; padding-right: 50px">
    <div class="row">
        <h4> CHANGE YOUR PASSWORD </h4>
    </div>

    <div class="form-group">
        {{ form.current}}
        <!--<input type="password" placeholder="Current Password" class="form-control"></input> -->
    </div>

    <div class="form-group">
        {{ form.new }}
       <!-- <input type="password" placeholder="New Password" class="form-control"></input> -->
    </div>

    <div class="form-group">
        {{ form.reenter }}
       <!-- <input type="password" placeholder="Re-enter Password" class="form-control"></input> -->
    </div>

    <div class="form-group">         
        <input type="submit" value="SUBMIT" class="form-control btn btn-success"></input>
    </div>
    
  </div>
</form>
	

{% endblock content %}

app1/templates/app1/detector_checkDocument.html
{% extends 'app1/detectorHome.html' %}

{% block content %}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    {{ message | safe }}
	</div>
{% endfor %}
    <form class="form-horizontal" method="POST" enctype="multipart/form-data" style="display: flex; justify-content: center;">
        {% csrf_token %}
        <div class="form-group" style="padding-left: 50px; padding-right: 50px">
            <div class="row">
                
                    <h4> CHECK DOCUMENT </h4>
                
            </div>

            <div class="form-group">
                
                    {{ form.document }}
                
            </div>

            <div class="form-group">
                
                    <button type="submit" class="form-control btn btn-success">Upload</button>
                
            </div>
    
        </div>
    </form>

{% endblock content %}

app1/templates/app1/detector_history.html
{% extends 'app1/detectorHome.html' %}

{% comment %} Extraction function {% endcomment %}
{% block content %}
    <div class="row">
        <div class="container" style="height:40vh;overflow:auto;">
            <table class="table table-striped">
                <thead style="background-color: gainsboro; color: black;">
                <tr>
                    <th class="text-center">FileName</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Username</th>
                    <th class="text-center">ClientID</th>
                    <th class="text-center">Date</th>
                </tr>
                </thead>
                <tbody>
                {% for file in data %}
                        {% csrf_token %}
                        <tr><td>{{ file.document }}</td>
                            <td>{{ file.status }}</td>
                        <td>{{ file.username }}</td>
                        <td>{{ file.clientid }}</td>
                        <td>{{ file.uploaded_at }}</td>
                        </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

app1/templates/app1/userHome.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>User Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <style>
    *{
      overflow: hidden;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand navbar-colored" href="#">CSE3501</a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Sign Out </a></li>
        </ul>
	
    </div>
</nav>

<div class="row color2">
    <div class="col-6 text-center">
        <h4><p class="color1">Access level : {{ designation }}</p></h4>
    </div>
</div>

<div class="row">
    <div class="row container" style="margin-left: 0.1rem">
        <ul class="nav nav-tabs">
            <li class="{% if nbar == 'home' %}active{% endif %}"><a href="/user/userhome/">Home</a></li>
            <li class="{% if nbar == 'changepass' %}active{% endif %}"><a href="/user/changepassword/">Change Password</a></li>
            <li class="{% if nbar == 'displaydoc' %}active{% endif %}"><a href="/user/displayfiles/">Display Documents</a></li>
            <li class="{% if nbar == 'uploaddoc' %}active{% endif %}"><a href="/user/upload/">Upload Documents</a></li>
            <li class="{% if nbar == 'deletedoc' %}active{% endif %}"> <a href="/user/deletefile/">Manipulate Document</a></li>
        </ul>
    </div>

    <div class="row text-center">
        {% block content %}
    

        {% endblock %}
    </div><!--end of column2-->


</div><!-- end of central block -->
    <div class="row text-right" style = " background-color: #f1fff1; positon:sticky ; bottom: 0; padding: 0">
      <p style="padding: 0; margin-right: 50px; margin-bottom:0;"><em>Username: </em><b class="color2" style="color: #1111ff;"> {{ username }}</b></p>
    </div>
</body>
</html>

app1/templates/app1/user_changePassword.html
{% extends 'app1/userHome.html' %}

{% block content %}
  <form class="form-horizontal" method="POST" style="display: flex; justify-content: center;">
  {% csrf_token %}  
  <div class="form-group" style="padding-left: 50px; padding-right: 50px;">
    <div class="row">
        <h4> CHANGE YOUR PASSWORD </h4>
    </div>

    <div class="form-group">
        {{ form.current}}
        <!--<input type="password" placeholder="Current Password" class="form-control"></input> -->
    </div>

    <div class="form-group">
        {{ form.new }}
       <!-- <input type="password" placeholder="New Password" class="form-control"></input> -->
    </div>

    <div class="form-group">
        {{ form.reenter }}
       <!-- <input type="password" placeholder="Re-enter Password" class="form-control"></input> -->
    </div>

    <div class="form-group">         
        <input type="submit" value="SUBMIT" class="form-control btn btn-success"></input>
    </div>
    
  </div>
</form>
  

{% endblock content %}

app1/templates/app1/user_deleteDocument.html
{% extends 'app1/userHome.html' %}

{% block content %}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    {{ message | safe }}
	</div>
{% endfor %}
    <div class="row">
        <div class="container" style="height:40vh;overflow:auto;">
            <table class="table table-striped">
                <thead style="background-color: gainsboro; color: black;">
                <tr>
                    <th class="text-center">Title</th>
                    <th class="text-center">Description</th>
                    <th class="text-center"></th>
                </tr>
                </thead>
                <tbody>  
                {% for file in data %}
                    <form method="POST">
                        {% csrf_token %}
                        <tr><td>{{ file.title }}</td>
                            <td>{{ file.description }}</td>
                            <td><button type="submit" class="form-control btn btn-success" name="filename" value="{{ file.document }}"> Manipulate and Delete </button></td>
                        </tr>
                    </form>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

app1/templates/app1/user_searchDocument.html
{% extends 'app1/userHome.html' %}

 {% block content %}
     
     <div class="row">
         <div class="container" style="height:40vh;overflow:auto;">
             <table class="table table-striped">
                <thead style="background-color: gainsboro; color: black;">
                  <tr>
                    <th class="text-center">Title</th>
                    <th class="text-center">Description</th>
                    <th class="text-center"></th>
                  </tr>
                </thead>
                <tbody>  
                 {% for file in data %}
                     <form method="POST">
                         {% csrf_token %}
                         <tr><td>{{ file.title }}</td>
                             <td>{{ file.description }}</td>
                             <td><button type="submit" class="form-control btn btn-success" name="filename" value="{{ file.document }}"> Access </button></td>
                         </tr>
                     </form>
                 {% endfor %}
                </tbody>
             </table>
         </div>
     </div>
 {% endblock content %}

app1/templates/app1/user_uploadDocument.html
{% extends 'app1/userHome.html' %}

{% block content %}
    <form class="form-horizontal" method="POST" enctype="multipart/form-data" style="display: flex; justify-content: center;">
        {% csrf_token %}
        <div class="form-group" style="padding-left: 50px; padding-right: 50px">
            <div class="row">
                    <h4> UPLOAD DOCUMENT </h4>
            </div>

            <div class="form-group">
                    <!-- <input type="text" placeholder="Title" class="form-control"></input> -->
                    {{ form.title }}
            </div>

            <div class="form-group">
                    <!-- <textarea class="form-control" rows="5" placeholder="Description"></textarea> -->
                    {{ form.description }}
            </div>
            <div class="form-group">
                    <!-- <textarea class="form-control" rows="5" placeholder="Description"></textarea> -->
                    {{ form.accesslevel }}
            </div>
            <div class="form-group">
                    <!-- <textarea class="form-control" rows="5" placeholder="Description"></textarea> -->
                    {% comment %} {{ form.document }}
                     {% endcomment %}
                     <input type="file" name="document" required="" id="id_document" multiple>
            </div>

            <div class="form-group">
                    <button type="submit" class="form-control btn btn-success">Upload</button>
            </div>
    
        </div>
    </form>
  

{% endblock content %}